name: supa_sample
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7

  # Supabase
  supabase_flutter: ^2.3.4

  # State Management
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^16.2.0

  # Environment & Config
  flutter_dotenv: ^6.0.0

  # Local Storage
  shared_preferences: ^2.2.2
  intl: ^0.20.2

  # Dosya ve izin yönetimi
  permission_handler: ^11.3.0
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # HTTP istekleri
  http: ^1.2.0
  dio: ^5.4.0 # Gelişmiş HTTP client

  # Dosya operasyonları
  path: ^1.8.3
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.7
  json_annotation: ^4.8.1

  # App Configuration
  flutter_launcher_icons: ^0.14.4

# App Icon Configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - .env
